In [2]:
import pandas as pd
import numpy as np

# 1 Creating a dataframe from an array

## 1.1 Option 1

In [3]:
#creating an array
data = np.array([[1,4],[2,5],[3,6]])

In [5]:
#creating a dataframe
df = pd.DataFrame(data, index=['row1','row2', 'row3'], columns=['col1','col2'])

In [6]:
#showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

## 1.2 Option 2

In [ ]:
# creating an array with list shape without numpy
data = [[1,4],[2,5],[3,6]]

In [ ]:
#creating a dataframe
df = pd.DataFrame(data, index=['row1','row2', 'row3'], columns=['col1','col2'])

In [7]:
#showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# 2 Creating a DataFrame from a dictionary

In [8]:
# lists used for this example
states = ["California", "Texas", "Florida", "New York"]
population = [39613493, 29730311, 21944577, 19299981]

In [11]:
# Storing lists within a dictionary
dict_states = {'States':states, 'Population':population}

In [12]:
# Creating the dataframe
df_population = pd.DataFrame(dict_states)

In [13]:
# showing the datafrane
df_population

       States  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

# 3 Creating a DataFrame from a csv file

In [14]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [17]:
# show first 5 rows in a data frame
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75